from enum import enum

class_state = enum('TIMEOUT','RECEIVED','TRANSMITTED','IDLE','NOT_RECEIVED')

phone_state = enum('INCREMENT_AND_WAIT','CHECK_AND_WAIT','REQUEST_AND_WAIT','ERROR_CHECK','ENCRYPT_AND_WAIT','IDLE')

station_state = enum('INCREMENT_AND_WAIT','CHECK_AND_WAIT','REQUEST_AND_WAIT','ERROR_CHECK','ENCRYPT_AND_WAIT','IDLE')

